name: Container

on:
  workflow_call:
    inputs:
      ORGANISATION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
          required: true
      DOCKER_PASSWORD:
          required: true

jobs:

    container:
        name: 'Container'
        runs-on: ubuntu-latest
        environment:  ${{ inputs.ENVIRONMENT }}
        env:
            ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
            ORGANISATION: ${{ inputs.ORGANISATION }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: 'Show Variables'
          run: |
            sh ./tools_platform/environment_variables.sh
    
        - name: Docker Build & Push
          run: |
            sh ./tools_app/docker_build_push.sh True

        - name: Docker Run
          run: |
            sh ./tools_app/docker_run_stop.sh True

        - name: Install curl
          run: |
            sudo apt-get update && sudo apt-get install -y curl

        - name: Docker Test
          run: |
            sh ./test/test_simple.sh
        


  